#!/system/bin/sh

(
# Wait until we see some android processes to consider boot is more or less complete
while ! pgrep system_server; do
  sleep 1
done

SOOPLUS_CONF="/system/etc/sooplus.conf"
SOOPLUS_LOGFILE="/sdcard/sooplus.log"

if [ -f $SOOPLUS_LOGFILE ]; then
  mv $SOOPLUS_LOGFILE $SOOPLUS_LOGFILE.2;
fi

echo $(date) >> $SOOPLUS_LOGFILE

echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 300000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo 2265600 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 2265600 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq

#vibrator settings
GVIB=`grep "GVIB" $SOOPLUS_CONF | cut -d '=' -f2`
echo $GVIB > /sys/class/timed_output/vibrator/amp
echo Vibration strength\: $GVIB >> $SOOPLUS_LOGFILE;

#Set Wake Gestures
#if [ "`grep WG=1 $SOOPLUS_CONF`" ]; then
#  echo 1 > /sys/android_touch/wake_gestures
#  echo Wake gestures enabled >> $SOOPLUS_LOGFILE;
#else
#  echo 0 > /sys/android_touch/wake_gestures
#  echo Wake gestures disabled >> $SOOPLUS_LOGFILE;
#fi

#disable wake gestures on lollipop until xposed work on lollipop
echo 0 > /sys/android_touch/wake_gestures

#Set Sweep2wake
S2W="`grep SWEEP2WAKE $SOOPLUS_CONF | cut -d '=' -f2`"
  echo $S2W > /sys/android_touch/sweep2wake
  echo Sweep2wake $S2W >> $SOOPLUS_LOGFILE;

#Set Doubletap2wake
if [ "`grep DT2W=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/android_touch/doubletap2wake
  echo Doubletap2wake enabled >> $SOOPLUS_LOGFILE;
elif [ "`grep DT2W=2 $SOOPLUS_CONF`" ]; then
  echo 2 > /sys/android_touch/doubletap2wake
  echo Doubletap2wake fullscreen enabled >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/android_touch/doubletap2wake
  echo Doubletap2wake disabled >> $SOOPLUS_LOGFILE;
fi

#Set Sweep2sleep
if [ "`grep S2S=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/android_touch/sweep2sleep
  echo Sweep2sleep right enabled >> $SOOPLUS_LOGFILE;
elif [ "`grep S2S=2 $SOOPLUS_CONF`" ]; then
  echo 2 > /sys/android_touch/sweep2sleep
  echo Sweep2sleep left enabled >> $SOOPLUS_LOGFILE;
elif [ "`grep S2S=3 $SOOPLUS_CONF`" ]; then
  echo 3 > /sys/android_touch/sweep2sleep
  echo Sweep2sleep left and right enabled >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/android_touch/sweep2sleep
  echo Sweep2sleep disabled >> $SOOPLUS_LOGFILE;
fi

#Set Wake vibration strength
VIB_STRENGTH="`grep VIB_STRENGTH $SOOPLUS_CONF | cut -d '=' -f2`"
  echo $VIB_STRENGTH > /sys/android_touch/vib_strength
  echo Wake vibration strength $VIB_STRENGTH >> $SOOPLUS_LOGFILE;

#Set S2W/DT2W Power Key Toggle
if [ "`grep PWR_KEY=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/module/qpnp_power_on/parameters/pwrkey_suspend
  echo "Power key toggle for S2W/DT2W enabled" >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/module/qpnp_power_on/parameters/pwrkey_suspend
  echo "Power key toggle for S2W/DT2W disabled" >> $SOOPLUS_LOGFILE;
fi

#Set S2W/DT2W Timeout
TIMEOUT=`grep "TIMEOUT" $SOOPLUS_CONF | cut -d '=' -f2`
echo $TIMEOUT > /sys/android_touch/wake_timeout
echo S2W/DT2W Timeout\: $TIMEOUT >> $SOOPLUS_LOGFILE;

#Set FASTCHARGE
if [ "`grep FC=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/kernel/fast_charge/force_fast_charge
  echo USB Fastcharge enabled >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/kernel/fast_charge/force_fast_charge
  echo USB Fastcharge disabled >> $SOOPLUS_LOGFILE;
fi

#Set Bricked MPdecision on/off
if [ "`grep BMPDEC=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/kernel/msm_mpdecision/conf/enabled
  echo "Bricked MPdecision & thermal enabled" >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/kernel/msm_mpdecision/conf/enabled
  echo "Bricked MPdecision disabled and qcom mpdec and thermal enabled" >> $SOOPLUS_LOGFILE;
fi

#Set Bricked MPdecision touch boost
if [ "`grep MPTB=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/kernel/msm_mpdecision/conf/boost_enabled
  echo "Bricked MPdecision touch boost enabled" >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/kernel/msm_mpdecision/conf/boost_enabled
  echo "Bricked MPdecision touch boost disabled" >> $SOOPLUS_LOGFILE;
fi

#multicore power saving
if [ "`grep MPS=1 $SOOPLUS_CONF`" ]; then
  echo 2 > /sys/devices/system/cpu/sched_mc_power_savings
  echo "multicore power saving aggressive enabled" >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/devices/system/cpu/sched_mc_power_savings
  echo "multicore power saving disabled" >> $SOOPLUS_LOGFILE;
fi

# Governor
if [ "`grep CPU=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/devices/system/cpu/cpu0/online;
  echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu1/online;
  echo interactive > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu2/online;
  echo interactive > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu3/online;
  echo interactive > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
  echo interactive CPU governor >> $SOOPLUS_LOGFILE;
else
  echo 1 > /sys/devices/system/cpu/cpu0/online;
  echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu1/online;
  echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu2/online;
  echo ondemand > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
  echo 1 > /sys/devices/system/cpu/cpu3/online;
  echo ondemand > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
  echo Ondemand CPU governor >> $SOOPLUS_LOGFILE;
fi

#io scheduler settings
#SCHED=`grep "SCHED" $SOOPLUS_CONF | cut -d '=' -f2`
#if [ "`grep SCHED=1 $SOOPLUS_CONF`" ]; then
#  echo cfq > /sys/block/mmcblk0/queue/scheduler;
#  echo CFQ io scheduler >> $SOOPLUS_LOGFILE;
#elif [ "`grep SCHED=3 $SOOPLUS_CONF`" ]; then
#  echo deadline > /sys/block/mmcblk0/queue/scheduler;
#  echo deadline io scheduler >> $SOOPLUS_LOGFILE;
#elif [ "`grep SCHED=4 $SOOPLUS_CONF`" ]; then
#  echo noop > /sys/block/mmcblk0/queue/scheduler;
#  echo Noop io scheduler >> $SOOPLUS_LOGFILE;
#elif [ "`grep SCHED=5 $SOOPLUS_CONF`" ]; then
#  echo fiops > /sys/block/mmcblk0/queue/scheduler;
#  echo fiops io scheduler >> $SOOPLUS_LOGFILE;
#else
#  echo row > /sys/block/mmcblk0/queue/scheduler;
#  echo ROW io scheduler >> $SOOPLUS_LOGFILE;
#fi

#Readahead settings
READAHEAD=`grep "READAHEAD" $SOOPLUS_CONF | cut -d '=' -f2`
echo $READAHEAD > /sys/block/mmcblk0/queue/read_ahead_kb
echo Readahead size\: $READAHEAD >> $SOOPLUS_LOGFILE;

#Set Backlight
if [ "`grep BL=1 $SOOPLUS_CONF`" ]; then
  echo 1 > /sys/module/lm3630_bl/parameters/backlight_dimmer
  echo Backlight dimmer enabled >> $SOOPLUS_LOGFILE;
else
  echo 0 > /sys/module/lm3630_bl/parameters/backlight_dimmer
  echo Backlight dimmer disabled >> $SOOPLUS_LOGFILE;
fi

#Set Faux Sound
#Quality profile
if [ "`grep FS=1 $SOOPLUS_CONF`" ]; then
  echo "0" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "0" > /sys/kernel/sound_control_3/gpl_cam_mic_gain;
  echo "254 254" > /sys/kernel/sound_control_3/gpl_headphone_gain;
  echo "33 33" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain;
#  echo "0" > /sys/kernel/sound_control_3/gpl_mic_gain;
  echo "254 254" > /sys/kernel/sound_control_3/gpl_speaker_gain;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_rec_locked;
  echo Faux sound Quality profile enabled >> $SOOPLUS_LOGFILE;
#Loudness profile
elif [ "`grep FS=2 $SOOPLUS_CONF`" ]; then
  echo "0" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "0" > /sys/kernel/sound_control_3/gpl_cam_mic_gain;
  echo "9 9" > /sys/kernel/sound_control_3/gpl_headphone_gain;
  echo "35 35" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain;
#  echo "0" > /sys/kernel/sound_control_3/gpl_mic_gain;
  echo "5 5" > /sys/kernel/sound_control_3/gpl_speaker_gain;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_rec_locked;
  echo Faux sound Loudness profile enabled >> $SOOPLUS_LOGFILE;
elif [ "`grep FS=3 $SOOPLUS_CONF`" ]; then
  echo "0" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "0" > /sys/kernel/sound_control_3/gpl_cam_mic_gain;
  echo "251 251" > /sys/kernel/sound_control_3/gpl_headphone_gain;
  echo "40 40" > /sys/kernel/sound_control_3/gpl_headphone_pa_gain;
#  echo "0" > /sys/kernel/sound_control_3/gpl_mic_gain;
  echo "253 253" > /sys/kernel/sound_control_3/gpl_speaker_gain;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_locked;
#  echo "1" > /sys/kernel/sound_control_3/gpl_sound_control_rec_locked;
  echo Faux sound Quiet profile enabled >> $SOOPLUS_LOGFILE;
else
  echo No Faux Sound profile enabled >> $SOOPLUS_LOGFILE;
fi

#Color presets
#Neriamarillo v3
if [ "`grep CP=1 $SOOPLUS_CONF`" ]; then
  #  Red Positive                = /sys/module/dsi_panel/kgamma_rp
  echo "0 10 17 27 37 45 57 75 86 105 117 125 125 119 113 100 85 75 67 61 52 37 21" > /sys/module/dsi_panel/kgamma_rp;
  #  Red Negative                = /sys/module/dsi_panel/kgamma_rn
  echo "0 10 17 27 37 45 57 75 86 105 117 125 125 119 113 100 85 75 67 61 52 37 21" > /sys/module/dsi_panel/kgamma_rn;
  #  Green Positive              = /sys/module/dsi_panel/kgamma_gp
  echo "83 85 86 88 91 94 101 111 115 127 132 136 115 111 106 94 78 69 63 57 49 36 20" > /sys/module/dsi_panel/kgamma_gp;
  #  Green Negative              = /sys/module/dsi_panel/kgamma_gn
  echo "83 85 86 88 91 94 101 111 115 127 132 136 115 111 106 94 78 69 63 57 49 36 20" > /sys/module/dsi_panel/kgamma_gn;
  #  Blue Positive               = /sys/module/dsi_panel/kgamma_bp
  echo "90 91 93 95 98 100 105 114 116 128 131 135 117 112 106 92 75 65 56 48 36 29 16" > /sys/module/dsi_panel/kgamma_bp;
  #  Blue Negative               = /sys/module/dsi_panel/kgamma_bn
  echo "90 91 93 95 98 100 105 114 116 128 131 135 117 112 106 92 75 65 56 48 36 29 16" > /sys/module/dsi_panel/kgamma_bn;
  #  White Point                 = /sys/module/dsi_panel/kgamma_w
  echo "32" > /sys/module/dsi_panel/kgamma_w;
  echo Neriamarillo v3 color profile enabled >> $SOOPLUS_LOGFILE;
#Yorici Calibrated Punch
elif [ "`grep CP=2 $SOOPLUS_CONF`" ]; then
  #  Red Positive                = /sys/module/dsi_panel/kgamma_rp
  echo "0 18 23 36 45 54 63 80 91 107 118 126 124 118 110 94 74 57 43 35 26 10 5" > /sys/module/dsi_panel/kgamma_rp;
  #  Red Negative                = /sys/module/dsi_panel/kgamma_rn
  echo "0 18 23 36 45 54 63 81 91 107 118 126 124 118 110 93 73 56 43 36 25 10 5" > /sys/module/dsi_panel/kgamma_rn;
  #  Green Positive              = /sys/module/dsi_panel/kgamma_gp
  echo "0 20 30 43 50 57 67 85 95 110 121 128 122 116 108 94 74 55 43 35 26 10 5" > /sys/module/dsi_panel/kgamma_gp;
  #  Green Negative              = /sys/module/dsi_panel/kgamma_gn
  echo "0 20 31 43 50 57 67 84 95 111 120 128 122 116 109 93 73 55 41 34 24 10 5" > /sys/module/dsi_panel/kgamma_gn;
  #  Blue Positive               = /sys/module/dsi_panel/kgamma_bp
  echo "0 14 18 31 41 47 59 77 88 105 116 125 125 119 111 95 75 56 48 37 26 15 5" > /sys/module/dsi_panel/kgamma_bp;
  #  Blue Negative               = /sys/module/dsi_panel/kgamma_bn
  echo "0 14 19 33 41 46 60 77 88 105 116 123 125 119 111 95 76 57 41 36 24 15 5" > /sys/module/dsi_panel/kgamma_bn;
  #  White Point                 = /sys/module/dsi_panel/kgamma_w
  echo "31" > /sys/module/dsi_panel/kgamma_w;
  echo Yorici v3 color profile enabled >> $SOOPLUS_LOGFILE;
#Piereligio True RGB v7
elif [ "`grep CP=3 $SOOPLUS_CONF`" ]; then
  #  Red Positive                = /sys/module/dsi_panel/kgamma_rp
  echo "0 12 19 30 39 48 56 72 83 105 121 130 118 115 114 108 100 80 66 60 48 38 22" > /sys/module/dsi_panel/kgamma_rp;
  #  Red Negative                = /sys/module/dsi_panel/kgamma_rn
  echo "0 12 19 30 39 48 56 72 83 105 119 130 119 115 116 106 88 80 71 62 52 42 25" > /sys/module/dsi_panel/kgamma_rn;
  #  Green Positive              = /sys/module/dsi_panel/kgamma_gp
  echo "0 12 20 31 40 55 62 79 84 109 123 134 116 112 112 104 101 76 67 58 49 39 21" > /sys/module/dsi_panel/kgamma_gp;
  #  Green Negative              = /sys/module/dsi_panel/kgamma_gn
  echo "0 12 20 31 40 55 62 76 89 109 123 132 115 113 111 103 78 75 67 58 49 39 21" > /sys/module/dsi_panel/kgamma_gn;
  #  Blue Positive               = /sys/module/dsi_panel/kgamma_bp
  echo "0 12 19 30 39 48 56 72 82 104 118 131 120 116 114 107 100 78 66 60 44 35 20" > /sys/module/dsi_panel/kgamma_bp;
  #  Blue Negative               = /sys/module/dsi_panel/kgamma_bn
  echo "0 12 19 30 39 48 56 72 82 104 118 127 119 116 115 106 84 78 66 60 44 35 20" > /sys/module/dsi_panel/kgamma_bn;
  #  White Point                 = /sys/module/dsi_panel/kgamma_w
  echo "32" > /sys/module/dsi_panel/kgamma_w;
  echo Piereligio True RGV v7 color profile enabled >> $SOOPLUS_LOGFILE;
else
  echo No color profile enabled >> $SOOPLUS_LOGFILE;
fi

#update saved config
cp /system/etc/sooplus.conf /sdcard/.sooplus.backup

) & 

if pgrep logwrapper; then
    killall logwrapper
    echo logwrapper killed >> $SOOPLUS_LOGFILE;
fi

exit 0
